# Generated by Django 2.0.13 on 2019-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20190505_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='aula',
            name='video',
            field=models.CharField(default='', max_length=800),
        ),
    ]
