# Generated by Django 2.0.13 on 2019-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_auto_20190505_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='assuntos',
            field=models.CharField(choices=[('ECA', 'ENTENDENDO A CONTAMINAÇÃO DOS ALIMENTOS'), ('AMA', 'AMBIENTE DE MANIPULAÇÃO E CUIDADOS COM ÁGUA'), ('MLV', 'MANUSEIO DO LIXO E CONTROLE DE VETORES E PRAGAS'), ('HIG', 'HIGIENIZAÇÃO'), ('MEV', 'MANIPULADORES E VISITANTES'), ('EDM', 'ETAPAS DA MANIPULAÇÃO'), ('DOC', 'DOCUMENTAÇÃO')], default='', max_length=3),
        ),
    ]
